name: TVShow Tracker

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Create binaries
      run: pyinstaller tv_tracker.pyw -F -n "TVShow Tracker" -i "images/app.ico" --add-data images;images
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "dist/TVShow Tracker.exe"
        skipIfReleaseExists: true
